# Generated by Django 6.0.5 on 2026-05-18 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_todo_completed'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='users',
            field=models.ManyToManyField(blank=True, related_name='assigned_todos', to=settings.AUTH_USER_MODEL),
        ),
    ]
